### ISSUE TITLE
Boxplots

### ISSUE THREAD

**Issue by jadianes** [PRIDE-Cluster/cluster-web-app#28]
After some discussion, it seems that boxplots are needed to represent the confidence charts in the Cluster detail page. However the libraries of directive we know about (NVD3-based) does not provide this type of chart.  

Therefore, we need to define our own D3 boxplot and embed it in an AngularJS directive so it can be used in the Cluster details page.

**Comment by ruiwanguk** [comment]
@jadianes I will try to deploy the web service today for the boxplots.
